package com.google.android.apps.common.testing.accessibility.framework.suggestions;

import com.google.android.apps.common.testing.accessibility.framework.AccessibilityHierarchyCheckResult;
import com.google.android.apps.common.testing.accessibility.framework.checks.EditableContentDescCheck;
import com.google.common.collect.ImmutableList;

/**
 * A {@link FixSuggestionsProvider} which provides suggestions to fix a {@link
 * AccessibilityHierarchyCheckResult} generated by an {@link EditableContentDescCheck},
 *
 * <p>If the culprit TextView is labeled by a contentDescription, provides an immutable list with
 * one suggestion that recommends removing the {@code contentDescription} view attribute. Otherwise
 * no fix suggestions will be provided.
 */
class EditableContentDescFixSuggestionsProvider
    extends BaseFixSuggestionsProvider<EditableContentDescCheck> {

  private static final ImmutableList<FixSuggestionProducer<? extends FixSuggestion>>
      FIX_SUGGESTION_PRODUCERS = ImmutableList.of(new EditableContentDescProducer());

  @Override
  protected ImmutableList<FixSuggestionProducer<? extends FixSuggestion>>
      getFixSuggestionProducers() {
    return FIX_SUGGESTION_PRODUCERS;
  }

  @Override
  protected Class<EditableContentDescCheck> getTargetCheckClass() {
    return EditableContentDescCheck.class;
  }
}
