package com.google.android.apps.common.testing.accessibility.framework.suggestions;

import com.google.android.apps.common.testing.accessibility.framework.AccessibilityHierarchyCheckResult;
import com.google.android.apps.common.testing.accessibility.framework.checks.RedundantDescriptionCheck;
import com.google.common.collect.ImmutableList;

/**
 * A {@link FixSuggestionsProvider} which provides fix suggestions to a {@link
 * AccessibilityHierarchyCheckResult} generated by {@link RedundantDescriptionCheck}.
 */
class RedundantDescriptionFixSuggestionsProvider
    extends BaseFixSuggestionsProvider<RedundantDescriptionCheck> {

  private static final ImmutableList<FixSuggestionProducer<? extends FixSuggestion>>
      FIX_SUGGESTION_PRODUCERS = ImmutableList.of(new RedundantDescriptionFixSuggestionProducer());

  @Override
  protected ImmutableList<FixSuggestionProducer<? extends FixSuggestion>>
      getFixSuggestionProducers() {
    return FIX_SUGGESTION_PRODUCERS;
  }

  @Override
  protected Class<RedundantDescriptionCheck> getTargetCheckClass() {
    return RedundantDescriptionCheck.class;
  }
}
