package com.google.android.apps.common.testing.accessibility.framework.suggestions;

import com.google.android.apps.common.testing.accessibility.framework.AccessibilityHierarchyCheckResult;
import com.google.android.apps.common.testing.accessibility.framework.checks.SpeakableTextPresentCheck;
import com.google.common.collect.ImmutableList;

/**
 * A {@link FixSuggestionsProvider} which provides suggestions to fix a {@link
 * AccessibilityHierarchyCheckResult} generated by an {@link SpeakableTextPresentCheck},
 *
 * <p>If the culprit View is missing speakable text, provides an immutable list with a {@link
 * SetViewAttributeFixSuggestion} which recommends setting the contentDescription view attribute.
 * Otherwise no fix suggestions will be provided.
 */
class SpeakableTextPresentFixSuggestionsProvider
    extends BaseFixSuggestionsProvider<SpeakableTextPresentCheck> {

  private static final ImmutableList<FixSuggestionProducer<? extends FixSuggestion>>
      FIX_SUGGESTION_PRODUCERS = ImmutableList.of(new SpeakableTextPresentFixSuggestionProducer());

  @Override
  protected ImmutableList<FixSuggestionProducer<? extends FixSuggestion>>
      getFixSuggestionProducers() {
    return FIX_SUGGESTION_PRODUCERS;
  }

  @Override
  protected Class<SpeakableTextPresentCheck> getTargetCheckClass() {
    return SpeakableTextPresentCheck.class;
  }
}
