package com.google.android.apps.common.testing.accessibility.framework.suggestions;

import com.google.android.apps.common.testing.accessibility.framework.AccessibilityHierarchyCheckResult;
import com.google.android.apps.common.testing.accessibility.framework.checks.TextContrastCheck;
import com.google.common.collect.ImmutableList;

/**
 * A {@link FixSuggestionsProvider} which provides fix suggestions to an {@link
 * AccessibilityHierarchyCheckResult} generated by a {@link TextContrastCheck}.
 */
class TextContrastFixSuggestionsProvider extends BaseFixSuggestionsProvider<TextContrastCheck> {

  private static final ImmutableList<FixSuggestionProducer<? extends FixSuggestion>>
      FIX_SUGGESTION_PRODUCERS =
          ImmutableList.of(
              new TextColorFixSuggestionProducer(), new TextBackgroundColorFixSuggestionProducer());

  @Override
  protected ImmutableList<FixSuggestionProducer<? extends FixSuggestion>>
      getFixSuggestionProducers() {
    return FIX_SUGGESTION_PRODUCERS;
  }

  @Override
  protected Class<TextContrastCheck> getTargetCheckClass() {
    return TextContrastCheck.class;
  }
}
