/*
 * Copyright (C) 2017 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.google.android.apps.common.testing.accessibility.framework.replacements;

/**
 * Indicates that the implementing class is capable of serving as a replacement (for purposes of
 * accessibility evaluation) of a type {@link T} from the Android SDK, whose implementation is only
 * available in Android runtime environments.  It further indicates that an equivalent Android-only
 * instance of type {@link T} may be recreated from an instance of an implementing class with {@link
 * #getAndroidInstance}
 *
 * @param <T> the native Android-only type replaced by an implementing class
 */
public interface Replaceable<T> {

  /**
   * Creates a native Android-compatible object of type {@link T} that is acceptable for use in
   * Android environments.
   *
   * <p>NOTE: This method is intended to function only in Android runtime environments. Invoking
   * this in another runtime will result in {@link RuntimeException}s generated by Android's SDK
   * stub implementations.
   *
   * @return an instance of the Android-compatible class that is being replaced by this instance
   */
  public T getAndroidInstance();
}
